#Aws DB and Jpa and Jwt and debug setting
spring:
  server:
    port: 8080
    servlet:
      encoding:
        force-response: true

  # redis
  redis:
    host:
    port:

  # db
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # auto create schema
    hibernate:
      ddl-auto: update
    # show sql query
    show-sql: true
    # SQL pretty print
    properties:
      hibernate:
        format_sql: true
    # colorful console
    output:
      ansi:
        enabled: always
    # image size
    servlet:
      multipart:
        max-request-size: 10MB
        max-file-size: 10MB


#aws S3 setting
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


# jwt
jwt:
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 1440
mail:
  address:
    admin: admin@gmail.com


## configuration to put the actual value in sql query parameter
decorator.datasource.p6spy:
  enable-logging: true
  multiline: true


## logging above debugs
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG