#aws S3
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  application:
    name: gigker
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # auto create schema
    show-sql: true      # show sql query
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
  output:
    ansi:
      enabled: always   # colorful console
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: 8080
  servlet:
    encoding:
      force-response: true

# configuration to put the actual value in sql query parameter
decorator.datasource.p6spy:
  enable-logging: true
  multiline: true

# logging above debugs
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com

jwt:
#  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

#spring:
#  jpa:
#    database: mysql
#    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#
#
##  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://localhost:3306/gigkerdev?allowPublicKeyRetrieval=true&characterEncoding=UTF-8
##    username: ${MYSQL_NAME}
##    password: ${MYSQL_SECRET}
#
##  ssl:
##    key-store-type: PKCS12
##    key-store: classpath:localhost.p12      #HTTPS SETTING
##    key-password: changeit
#

