insert into tag (tag_id, tag_name) values (default, '당일지급'),
                                          (default, '친구와함께'),
                                          (default, '능력활용알바'),
                                          (default, '역세권'),
                                          (default, '관공서'),
                                          (default, '경력1년이상'),
                                          (default, '식사제공'),
                                          (default, '식대별도'),
                                          (default, '재택근무'),
                                          (default, '야간'),
                                          (default, '초보자가능'),
                                          (default, '최저시급'),
                                          (default, 'TEST'),
                                          (default, 'TEST2');

insert into category (category_id, category_name) values (default, '외식・카페'),
                                                         (default, '매장관리・판매'),
                                                         (default, '서비스'),
                                                         (default, '사무직'),
                                                         (default, '고객상담・리서치・영업'),
                                                         (default, '생산・건설・노무'),
                                                         (default, 'IT・기술'),
                                                         (default, '디자인'),
                                                         (default, '미디어'),
                                                         (default, '운전・배달'),
                                                         (default, '병원・간호・연구'),
                                                         (default, '교육・강사'),
                                                         (default, '기타');
